name: "Hosted: Network Filtering with Harden-Runner"
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95691d3d1cfc1f403f673ccbe70465d7c4254108
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            ghcr.io:443
            github.com:443
            registry.npmjs.org:443
            www.githubstatus.com:443

      - uses: crazy-max/ghaction-github-status@df4d23a4977438215339cf0fafceda8d9af8a0e5 # v4.0.0

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: npm install
        run: |
          cd ./src/exfiltration-demo
          npm install

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@3cf273023a0dda27efcd3164bdfb51908dd46a5b # v1.3.1
        with:
          path: src/exfiltration-demo

      - uses: madhead/semver-utils@6baf9abaf54c02482db5bf0e260e04ff031a0f5e # latest
        id: version
        with:
          version: 1.2.3

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@eb53b3ec07136a6ebaed78d8135806da64f7c7e2 # v5
        with:
          name: ${{ github.repository }}/prod:latest
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          workdir: ./src/exfiltration-demo
